#!/usr/bin/env python3
"""Cross-platform replacement for count-message.sh."""

from __future__ import annotations

import argparse
import pathlib
import re

_CONTENT_RE = re.compile(r".*:[0-9][0-9]:(.*)")
_BRACKET_RE = re.compile(r"\[.*?\]")


def clean_message_line(line: str) -> str:
    match = _CONTENT_RE.match(line.rstrip("\n"))
    text = match.group(1) if match else line.rstrip("\n")
    text = _BRACKET_RE.sub("", text)
    if "img" in text:
        return ""
    return text


def count_file(path: pathlib.Path) -> tuple[int, int, int]:
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    cleaned = [clean_message_line(line) for line in lines]
    chars = sum(len(line) for line in cleaned)
    words = sum(len(line.split()) for line in cleaned)
    return len(lines), chars, words


def main() -> int:
    parser = argparse.ArgumentParser(description="Count message lines/chars/words in dump-msg.py output.")
    parser.add_argument("directory", help="directory of .txt files generated by dump-msg.py")
    args = parser.parse_args()

    directory = pathlib.Path(args.directory)
    if not directory.is_dir():
        raise SystemExit(f"Not a directory: {directory}")

    rows = []
    for path in sorted(directory.glob("*.txt")):
        line_count, char_count, word_count = count_file(path)
        rows.append((path, line_count, char_count, word_count))
    rows.sort(key=lambda row: row[1])

    headers = ("Filename", "#Lines", "#Chars", "#Words")
    widths = [len(x) for x in headers]
    rendered = []
    for path, line_count, char_count, word_count in rows:
        row = (str(path), str(line_count), str(char_count), str(word_count))
        rendered.append(row)
        widths = [max(widths[i], len(row[i])) for i in range(4)]

    print("  ".join(headers[i].ljust(widths[i]) for i in range(4)))
    for row in rendered:
        print("  ".join(row[i].ljust(widths[i]) for i in range(4)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
